server:
  port: 8080
  undertow:
    buffer-size: 1024
    directBuffers: true
  servlet:
    session:
      timeout: 86400
spring:
  application:
    name: supermall
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySql配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/supermall?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

mybatis-plus:
  type-aliases-package: cn.xju.entity
  mapper-locations: classpath:/mapper/**.xml
